# Configuration file for 16S processing pipeline
# Lines starting with # are comments and will be ignored

# 16s data processing
# Path to directory containing raw fastq files
data_path = "/data/local/jy1008/project_folder/data/raw_fastq/"

# Patterns to match forward and reverse read files
pattern_forward = "_R1_001.fastq.gz"
pattern_reverse = "_R2_001.fastq.gz"

# Output directories
data_output_dir = "/data/local/jy1008/project_folder/test_data_output"
figure_output_dir = "/data/local/jy1008/project_folder/test_figure_output"

#Taxonomy database
taxonomy_db = "/data/local/jy1008/project_folder/database/silva_nr99_v138.2_toGenus_trainset.fa.gz"
taxonomy_db_species = "/data/local/jy1008/project_folder/database/silva_v138.2_assignSpecies.fa.gz"


# Processing parameters
truncLen_f = 151  # Forward read truncation length
truncLen_r = 151  # Reverse read truncation length
maxN = 0  # Maximum number of Ns allowed in a read
# maxEE kept at 1
# https://www.microbiologyresearch.org/content/journal/jmm/10.1099/jmm.0.001756
# https://www.nature.com/articles/s41467-025-57591-2
maxEE = 1  # Maximum expected error rate
# truncQ increased from 2 to 11 (more stringent)
# https://www.nature.com/articles/s41467-025-57591-2
truncQ = 11  # Truncation quality score

# These don't appear to be used
# Filtering parameters
# min_sample_count = 10  # Minimum number of samples where feature must be present in order to be kept
# thresh_range = (0,0.1,0.001)  # Vector of relative abundance threshold values to test
